'use strict';

module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.bulkInsert('Events', [
      // Scheduled Events
      {
        title: 'CES 2025 (Consumer Electronics Show)',
        date: '2025-01-07 10:00:00',
        description: 'CES 2025 is the world\'s most influential technology event, featuring over 4,300 exhibitors and 309 companies from 160 countries. The event showcases innovations in artificial intelligence, virtual reality, robotics, IoT, and sustainability. Keynote speakers include Jensen Huang of Nvidia, Tekedra N. Mawakana of Waymo, and Ed Bastian of Delta Air Lines.',
        type: 'scheduled',
        mentorId: null,
        profileId: null,
        creatorId: null,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'AFRICA and DESIGNCON TECHESPO',
        date: '2025-01-01 10:00:00',
        description: 'An upcoming technology expo focusing on design and innovation in Africa. Details regarding the date and location are yet to be announced.',
        type: 'scheduled',
        mentorId: null,
        profileId: null,
        creatorId: null,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // Live Webinars
      {
        title: 'Gartner Expert Q&A: How to Capture the Value Your Organization Wants From AI',
        date: '2025-01-08 07:00:00',
        description: 'A complimentary webinar where Gartner experts delve into how organizations can harness the value of artificial intelligence.',
        type: 'live',
        mentorId: null,
        profileId: null,
        creatorId: null,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'The Gartner Top Healthcare & Life Sciences Predictions for 2025',
        date: '2025-01-08 08:00:00',
        description: 'This session explores Gartner\'s predictions for the healthcare and life sciences sectors in 2025.',
        type: 'live',
        mentorId: null,
        profileId: null,
        creatorId: null,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Prepare for U.S. Administrative Change in Government IT',
        date: '2025-01-09 08:00:00',
        description: 'A webinar discussing strategies for government IT departments to adapt to administrative changes.',
        type: 'live',
        mentorId: null,
        profileId: null,
        creatorId: null,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'The 14 Power Skills You Need to Shape a Culture of Excellence',
        date: '2025-01-10 07:00:00',
        description: 'This session covers essential leadership skills for fostering a culture of excellence within organizations.',
        type: 'live',
        mentorId: null,
        profileId: null,
        creatorId: null,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // External Events
      {
        title: 'Tech Show London 2025',
        date: '2025-03-01 10:00:00',
        description: 'A prominent technology exhibition in London, showcasing the latest in tech innovations. Specific dates are yet to be announced.',
        type: 'external',
        mentorId: null,
        profileId: null,
        creatorId: null,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'RSA 2025',
        date: '2025-04-01 10:00:00',
        description: 'An annual conference focusing on cybersecurity, bringing together professionals to discuss the latest trends and challenges in the field. Details regarding the date are forthcoming.',
        type: 'external',
        mentorId: null,
        profileId: null,
        creatorId: null,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Computex Taipei 2025',
        date: '2025-06-01 10:00:00',
        description: 'Asia\'s largest computer and technology trade show, featuring a wide range of products and innovations. Exact dates are yet to be announced.',
        type: 'external',
        mentorId: null,
        profileId: null,
        creatorId: null,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'London Tech Week 2025',
        date: '2025-06-01 10:00:00',
        description: 'A week-long celebration of technology and innovation in London, with various events and exhibitions. Specific dates are pending.',
        type: 'external',
        mentorId: null,
        profileId: null,
        creatorId: null,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Microsoft Build 2025',
        date: '2025-05-01 10:00:00',
        description: 'Microsoft\'s annual developer conference, focusing on the latest in software development and cloud technologies. Details regarding the date are forthcoming.',
        type: 'external',
        mentorId: null,
        profileId: null,
        creatorId: null,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Black Hat USA 2025',
        date: '2025-08-01 10:00:00',
        description: 'A leading information security conference, offering briefings and training on the latest cybersecurity research and trends. Specific dates are yet to be announced.',
        type: 'external',
        mentorId: null,
        profileId: null,
        creatorId: null,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'AWS re:Invent 2025',
        date: '2025-11-01 10:00:00',
        description: 'Amazon Web Services\' annual conference, focusing on cloud computing and related technologies. Details regarding the date are forthcoming.',
        type: 'external',
        mentorId: null,
        profileId: null,
        creatorId: null,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ], {});
  },

  down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete('Events', null, {});
  }
};
